## YAML Template.
---
server:
  port: ${PORT:8080}

messages:
  home: Hello, Memorynotfound!

synbiohub:
  client:
    user: test
    email: test@test.com
    pass: testpass
    baseUrl: http://localhost:7777/
  cmd:
    # relative to src/main/java/ed/biordm/sbol/cli
    # the following is when packaged as WAR
    # properties: /WEB-INF/classes/cli/default.properties
    # the following is when packaged as JAR
    properties: /BOOT-INF/classes/cli/default.properties

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    # template-resolver-order:
    # view-names:
  main:
    banner-mode: off

logging:
  file:
    name: myapplication.log
#  level:
#    root:
#      - ".=info"
#      - "com.memorynotfound=debug"
#      - "org.springframework=info"