## YAML Template.
---
server:
  port: ${PORT:8080}

messages:
  home: Hello, Memorynotfound!

synbiohub:
  client:
    user: test
    email: test@test.com
    pass: testpass
    baseUrl: http://localhost:7777/
  cmd:
    # relative to src/main/java/ed/biordm/sbol/cli
    # the following is when packaged as WAR
    # properties: /WEB-INF/classes/cli/default.properties
    # the following is when packaged as JAR
    properties: /BOOT-INF/classes/cli/default.properties

spring:
  main:
    banner-mode: console
  banner:
    location: /BOOT-INF/classes/banner.txt

logging:
  file:
    name: myapplication.log
#  level:
#    root:
#      - ".=info"
#      - "com.memorynotfound=debug"
#      - "org.springframework=info"